# Generated by Django 3.0.3 on 2020-02-25 20:30

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20200225_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bruker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='epost'),
        ),
        migrations.AlterField(
            model_name='bruker',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='fornavn'),
        ),
        migrations.AlterField(
            model_name='bruker',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='etternavn'),
        ),
        migrations.AlterField(
            model_name='bruker',
            name='username',
            field=models.CharField(error_messages={'unique': 'Brukeren med dette brukernavn finnes allerede.'}, help_text='Påkrevd. 150 tegn eller færre. Bare bokstaver, sifre og @ /. / + / - / _.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
